USE jobfins_db;

-- Set valid BCrypt hash for 'password123'
-- Hash generated by BCryptPasswordEncoder: $2a$10$6e6wogFlqB4aIwsqI.wDxeH.qWcOLF4JspRp0oG61Bov.aceedCZW
UPDATE users SET password = '$2a$10$6e6wogFlqB4aIwsqI.wDxeH.qWcOLF4JspRp0oG61Bov.aceedCZW' WHERE email IN ('recruiter@jobfins.com', 'seeker@jobfins.com', 'priya.candidate@gmail.com');
